# 配置服务器端口，默认是8080，可以不用配置
server:
  port: 18080

spring:
  application:
    name: spring-boot-core
  profiles:
    active: dev
  jmx:   # 同时两个SpringBoot项目放在Tomcat webapps文件夹下启动，第二个项目会报unable to register MBean  加上该项配置，可解决
    enabled: false

elasticsearch:
  clustername: es5   # 集群名称  跟elasticsearch.yml中一样
  hosts: localhost      # 服务器ip
  port:  9300           # 默认 9300 是 Java 客户端的端口(即用java去连接es，需要访问这个端口)。9200 是支持 Restful HTTP 的接口