# 配置服务器端口，默认是8080，可以不用配置
server:
  port: 18080

spring:
  application:
    name: spring-boot-core
  profiles:
    active: dev

elasticsearch:
  clustername: elasticsearch
  hosts: 47.104.64.186
  port:  9300